### ISSUE TITLE
HALucinator Global Config should be generated if possible

### ISSUE THREAD

**Issue by diagprov** [HexHive/halucinator#4]
HALucinator has a global config file that is either installed to

     $VIRTUAL_ENV/etc/halucinator/config.yaml

or globally in

    /etc/halucinator/config.yaml

At the time of writing the file format looks like this:

```
---
arm_qemu_location: /home/ubuntu/qemu/bin/qemu-system-arm
avr_qemu_location: /home/ubuntu/qemu/bin/qemu-system-avr
qemu_debug: false
gdb_location: /usr/bin/gdb-multiarch
ipc:
    tx_port: 5556
    rx_port: 5555
```

arm_qemu and avr_qemu locations point to the build location of avatar-qemu. Absent any other need to build it, we could ship this or otherwise detect the location.

GDB0s entry is distribution-specific. For Fedora, GDB is multi-architecture and system GDB suffices. For Ubuntu, a specific multi-arch gdb must be installed (sudo apt-get install gdb-multiarch). As best as we can, we should detect the GDB required.
